CREATE TABLE fs_households (
    householdid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    householdname TEXT NOT NULL
);

ALTER TABLE fs_users
ADD userhousehold INTEGER REFERENCES fs_households(householdid) DEFAULT NULL;