CREATE TABLE households (
    householdid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    householdname TEXT NOT NULL
);

ALTER TABLE users
ADD userhousehold INTEGER REFERENCES households(householdid);