CREATE TABLE fs_chores (
    choreid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    chorename TEXT NOT NULL,
    chorehousehold INTEGER REFERENCES fs_households(householdid) NOT NULL,
    choreuser INTEGER REFERENCES fs_users(userid)
);